retry_count = 5
text_file_extensions = [
    ".md",
]

[[ignores]]
url = "https://twitter.com/kobae964/status/685820977784033281"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/kobae964/status/685820977784033281", # No alternatives
]

[[ignores]]
url = "https://twitter.com/kobae964/status/685853872867246081"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/kobae964/status/685853872867246081", # No alternatives
]

[[ignores]]
url = "https://twitter.com/kobae964/status/686201693453729792"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/kobae964/status/686201693453729792", # No alternatives
]

[[ignores]]
url = "https://twitter.com/kobae964/status/794866198206771204"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/kobae964/status/794866198206771204", # No alternatives
]

[[ignores]]
url = "https://twitter.com/kobae964/status/795293767875969025"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/kobae964/status/795293767875969025", # No alternatives
]

[[ignores]]
url = "https://twitter.com/kobae964/status/795294376909934592"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/kobae964/status/795294376909934592", # No alternatives
]

[[ignores]]
url = "https://twitter.com/viercc/status/1546791629843238917"
codes = [403]
reason = """
X does not allow access without login.
"""
considered_alternatives = [
    "https://twitter.com/viercc/status/1546791629843238917", # No alternatives
]

[[ignores]]
url = "https://www.sciencedirect.com/science/article/pii/0304397594000973"
codes = [403]
reason = "Always returns 403."
considered_alternatives = [
    "https://www.semanticscholar.org/paper/Fixed-Parameter-Tractability-and-Completeness-Downey-Fellows/ca84d533bbaf2563ea5d91bc944bb2d379550ae4",
]

[[ignores]]
url = "http://www.prefield.com/algorithm/dp/steiner_tree.html"
codes = [401]
reason = "Became private. Being a substring of a valid URL."
considered_alternatives = [
    "https://web.archive.org/web/20200222051102/http://www.prefield.com/algorithm/dp/steiner_tree.html",
]

[[ignores]]
url = "https://t.co/eUqnKnynQh"
has_tls_error = true
codes = [200]
reason = """https://zenn.dev/masaaania/articles/eeecaf1f1a08ee
Certificate the server provides is not valid (a part of the chain is returned).
"""
considered_alternatives = [
    "https://www.cs.bham.ac.uk//~pbl/cbpv.html",
]

[[ignores]]
url = "https://codeforces.com/gym/102028/problem/L"
codes = [403]
reason = """This URL returns 403 when accessed by GitHub Actions.
"""
considered_alternatives = [
    "https://codeforces.com/gym/102028/problem/L",
]

[[ignores]]
url = "https://codeforces.com/contest/1109/problem/D"
codes = [403]
reason = """This URL returns 403 when accessed by GitHub Actions.
"""
considered_alternatives = [
    "https://codeforces.com/contest/1109/problem/D",
]
